# Generated by Django 3.2 on 2023-09-12 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogId', models.PositiveSmallIntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Advocate', models.CharField(max_length=200)),
                ('Mobile', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('CaseNo', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('CaseYear', models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('CaseType', models.CharField(max_length=200)),
                ('CourtName', models.CharField(max_length=200)),
                ('CourtArea', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
