# Generated by Django 3.2 on 2023-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_blog_blogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='CourtArea',
            field=models.CharField(choices=[('new york', 'New York'), ('california', 'California'), ('iiiinois', 'IIIinois'), ('texas', 'Texas'), ('arizona', 'Arizona'), ('massachusetts', 'Massachusetts'), ('nevada', 'Nevada'), ('south carolina', 'South Carolina')], default='new york', max_length=30),
        ),
    ]
