# Generated by Django 3.2 on 2023-09-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20230912_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='check',
            new_name='Mobile_Updates',
        ),
    ]
